version: 2
updates:
  - package-ecosystem: "maven" 
    directory: "/" 
    schedule:
      interval: "daily"
 - package-ecosystem: "npm" 
   directory: "/react-app" 
   schedule:
      interval: "daily"
